name: Build and push docker images
description: Build and push docker images

inputs:
  name:
    description: "Name of the service to build and push to DockerHub"
    required: true

  username:
      description: "Username to login to Dockerhub"
      required: true

  password:
      description: "Password to login to Dockerhub"
      required: true
runs:
  using: composite

  steps:
  
      # Login to DockerHub 
    - name: login to DockerHub
      uses: docker/login-action@v3
      with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

    # Pushing image to DockerHub
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: giladkhaytin/tinderforfriends:latest
        context: inputs.name
