name : Build and deploy backend

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    # Access to the code
    - name: checkout code
      uses: actions/checkout@v4

    # Get changed files
    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44

    # Build and push
    - name : build and push backend
      if: contains(steps.changed-files.outputs.all_modified_files, 'backEnd/')
      uses: ./.github/actions/build-docker
      with:
        username : ${{ secrets.DOCKER_USERNAME }}
        password : ${{ secrets.DOCKER_PASSWORD }}
        name : backEnd

