name : Build and deploy backend

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v4

    # Get changed files
    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with :
        since_last_remote_commit: true

    - name: login to DockerHub
    # IF changed files are in backEnd folder
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
    # IF changed files are in backEnd folder
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: giladkhaytin/tinderforfriends:latest
        context: backEnd
