name : Build and deploy backend

on:

  push:
    branches: [ main ]

jobs:
  docker:
   
   runs-on: ubuntu-latest
   steps: 
   -
     name: checkout code
     uses: actions/checkout@v2
   -
     name: login to DockerHub
     uses: docker/login-action@v3
     with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   -
     name : build and push
     run: |
        docker build -t giladkhaytin/my-expo-dev:latest .
        docker push giladkhaytin/my-expo-dev:latest
