name : Build and deploy backend

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    # Access to the code
    - name: checkout code
      uses: actions/checkout@v4

    # Get changed files
    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with :
        since_last_remote_commit: true

    # Login to DockerHub 
    - name: login to DockerHub
      if: contains(steps.changed-files.outputs.all_modified_files, 'backEnd/')
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    # Pushing image to DockerHub
    - name: Build and push
      if: contains(steps.changed-files.outputs.all_modified_files, 'backEnd/')
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: giladkhaytin/tinderforfriends:latest
        context: backEnd
